### ISSUE TITLE
'Invalid path alias: @captchaRoute'

### ISSUE THREAD

**Issue by Mrpakistan** [jlorente/yii2-enhanced-captcha#1]
I can't install your extension yii2 gives the error Exception 'yii \ base \ InvalidArgumentException' with message 'Invalid path alias: @captchaRoute'

**Comment by jlorente** [comment]
Please be more precise. Have you follow the guide including the module in the bootstrap section of the config?

**Comment by Mrpakistan** [comment]
I found a problem. Sorry, that was my fault. Happy New Year :)
